apiVersion: v1
kind: Pod
metadata:
  name: simpleshop-products-api
  labels:
    app: simpleshop
    component: products-api
spec:
  containers:
    - name: products-api
      image: arber555/simpleshop-products-api:v1
      ports:
        - containerPort: 8080
      env:
        - name: PRODUCTS_DB_DSN
          value: "postgres://<username>:<password>@simpleshop-products-db:5432/<dbname>?sslmode=disable"
        - name: PORT
          value: "8080"
      volumeMounts:
        - name: log-volume
          mountPath: /logs
      resources:
        limits:
          memory: "256Mi"
          cpu: "250m"
  volumes:
    - name: log-volume
      emptyDir: {}
