apiVersion: v1
kind: Pod
metadata:
  name: simpleshop-stock-api
  labels:
    app: simpleshop
    component: stock-api
spec:
  containers:
    - name: stock-api
      image: arber555/simpleshop-stock-api:v1
      ports:
        - containerPort: 8081
      volumeMounts:
        - name: config-volume
          mountPath: /app/config
  volumes:
    - name: config-volume
      configMap:
        name: stock-config
