apiVersion: v1
kind: Service
metadata:
  name: simpleshop-web
  labels:
    app: simpleshop
spec:
  type: LoadBalancer
  ports:
    - port: 80         # Port exposed externally
      targetPort: 8080 # Port the container is listening on
  selector:
    app: simpleshop
    component: web